/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ExerciseAnswersRouteImport } from './routes/exercise-answers'
import { Route as McqsRouteImport } from './routes/mcqs'
import { Route as ModelQuestionsRouteImport } from './routes/model-questions'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as PastPapersRouteImport } from './routes/past-papers'
import { Route as QuestionBankRouteImport } from './routes/question-bank'
import { Route as SubjectClassIdSlugRouteImport } from './routes/subject.$classId.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ExerciseAnswersRoute = ExerciseAnswersRouteImport.update({
  id: '/exercise-answers',
  path: '/exercise-answers',
  getParentRoute: () => rootRouteImport,
} as any)
const McqsRoute = McqsRouteImport.update({
  id: '/mcqs',
  path: '/mcqs',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelQuestionsRoute = ModelQuestionsRouteImport.update({
  id: '/model-questions',
  path: '/model-questions',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const PastPapersRoute = PastPapersRouteImport.update({
  id: '/past-papers',
  path: '/past-papers',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionBankRoute = QuestionBankRouteImport.update({
  id: '/question-bank',
  path: '/question-bank',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectClassIdSlugRoute = SubjectClassIdSlugRouteImport.update({
  id: '/subject/$classId/$slug',
  path: '/subject/$classId/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/exercise-answers': typeof ExerciseAnswersRoute
  '/mcqs': typeof McqsRoute
  '/model-questions': typeof ModelQuestionsRoute
  '/notes': typeof NotesRoute
  '/past-papers': typeof PastPapersRoute
  '/question-bank': typeof QuestionBankRoute
  '/subject/$classId/$slug': typeof SubjectClassIdSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/exercise-answers': typeof ExerciseAnswersRoute
  '/mcqs': typeof McqsRoute
  '/model-questions': typeof ModelQuestionsRoute
  '/notes': typeof NotesRoute
  '/past-papers': typeof PastPapersRoute
  '/question-bank': typeof QuestionBankRoute
  '/subject/$classId/$slug': typeof SubjectClassIdSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/exercise-answers': typeof ExerciseAnswersRoute
  '/mcqs': typeof McqsRoute
  '/model-questions': typeof ModelQuestionsRoute
  '/notes': typeof NotesRoute
  '/past-papers': typeof PastPapersRoute
  '/question-bank': typeof QuestionBankRoute
  '/subject/$classId/$slug': typeof SubjectClassIdSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/exercise-answers'
    | '/mcqs'
    | '/model-questions'
    | '/notes'
    | '/past-papers'
    | '/question-bank'
    | '/subject/$classId/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/exercise-answers'
    | '/mcqs'
    | '/model-questions'
    | '/notes'
    | '/past-papers'
    | '/question-bank'
    | '/subject/$classId/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/exercise-answers'
    | '/mcqs'
    | '/model-questions'
    | '/notes'
    | '/past-papers'
    | '/question-bank'
    | '/subject/$classId/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ExerciseAnswersRoute: typeof ExerciseAnswersRoute
  McqsRoute: typeof McqsRoute
  ModelQuestionsRoute: typeof ModelQuestionsRoute
  NotesRoute: typeof NotesRoute
  PastPapersRoute: typeof PastPapersRoute
  QuestionBankRoute: typeof QuestionBankRoute
  SubjectClassIdSlugRoute: typeof SubjectClassIdSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercise-answers': {
      id: '/exercise-answers'
      path: '/exercise-answers'
      fullPath: '/exercise-answers'
      preLoaderRoute: typeof ExerciseAnswersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcqs': {
      id: '/mcqs'
      path: '/mcqs'
      fullPath: '/mcqs'
      preLoaderRoute: typeof McqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-questions': {
      id: '/model-questions'
      path: '/model-questions'
      fullPath: '/model-questions'
      preLoaderRoute: typeof ModelQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/past-papers': {
      id: '/past-papers'
      path: '/past-papers'
      fullPath: '/past-papers'
      preLoaderRoute: typeof PastPapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/question-bank': {
      id: '/question-bank'
      path: '/question-bank'
      fullPath: '/question-bank'
      preLoaderRoute: typeof QuestionBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subject/$classId/$slug': {
      id: '/subject/$classId/$slug'
      path: '/subject/$classId/$slug'
      fullPath: '/subject/$classId/$slug'
      preLoaderRoute: typeof SubjectClassIdSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ExerciseAnswersRoute: ExerciseAnswersRoute,
  McqsRoute: McqsRoute,
  ModelQuestionsRoute: ModelQuestionsRoute,
  NotesRoute: NotesRoute,
  PastPapersRoute: PastPapersRoute,
  QuestionBankRoute: QuestionBankRoute,
  SubjectClassIdSlugRoute: SubjectClassIdSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
